#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only or GPL-3.0-or-later


if [ "$(pwd)" = "$HOME/myCommands" ]; then
    cd $HOME
    echo "Adding $HOME/myCommands/executables to PATH ..."
    echo "export PATH=\"$PATH:$HOME/myCommands/executables\"" >> .profile
    cd myCommands
    echo "Compiling and enabling replacePhrase command ..."
    g++ srcCode/replaceFilePhrase/main.cpp -o executables/replacePhrase
    chmod 755 executables/replacePhrase
    echo "Finished"
else
    echo "Error: This directory myCommands/ must be placed inside your user home directory for this script to work properly."  
fi



